version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: image-moderation-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=image_moderation
    networks:
      - app-network

  # Backend service
  backend:
    build: ./backend
    container_name: image-moderation-backend
    ports:
      - "7000:7000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - DATABASE_NAME=image_moderation
      - TOKEN_SECRET_KEY=123xyz456
    networks:
      - app-network

  # Frontend service (optional if you're serving from backend)
  frontend:
    build: ./frontend
    container_name: image-moderation-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: